### ISSUE TITLE
Examples panic on window creation on Windows

### ISSUE THREAD

**Issue by matprec** [servo/glutin#143]
I've confirmed that this is not an upstream bug (tomaka/glutin). Their examples run just fine. This should narrow it down. I found this bug when trying to run webrender examples.

Hardware:
i7-8550U CPU
Intel UHD Graphics 620
Windows 10

Error:
```
PS C:\...\servo\glutin> cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\examples\window.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("CreateWindowEx function failed: Der Vorgang wurde erfolgreich beendet. (os error 0)")', src\libcore\result.rs:906:4
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:383
   3: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   5: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed<glutin::CreationError>
             at C:\projects\rust\src\libcore\macros.rs:23
  10: core::result::Result<glutin::Window, glutin::CreationError>::unwrap<glutin::Window,glutin::CreationError>
             at C:\projects\rust\src\libcore\result.rs:772
  11: window::main
             at .\examples\window.rs:17
  12: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  13: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:50
  14: main
  15: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  16: BaseThreadInitThunk
error: process didn't exit successfully: `target\debug\examples\window.exe` (exit code: 101)
```

How to reproduce (at least on my machine):
Run any example

**Comment by emilio** [comment]
We're working on unforking glutin and deprecate this crate: https://github.com/servo/servo/pull/19895

**Comment by atouchet** [comment]
Servo is now using upstream glutin.
